Hopin-inc/civicship-api

tsconfig.json

```
import { GraphQLError } from "graphql/error";
```
The intention here is to import from the graphql library, but tsc-alias was mistakenly treating it as an import from src/graphql/.
To address this, the configuration has been updated so that imports like import { hoge } from "graphql/*" will correctly resolve to node_modules/graphql/*.
上記でimportしたいのは、ライブラリとしてのgraphqlだが、
tsc-aliasが誤って、`src/graphql/`からimportするよう振る舞っていた。
そこで、`import { hoge }from "graphql/*"`と指定した際は、`node_modules/graphql/*`からimportするよう、設定を追記した。

FIX: Fix path alias resolution for imports from graphql

---

.github/workflows/deploy-to-cloud-run-dev.yml

`GCP_REGION` was hardcoded in GitHub workflow, so I have updated it to refer the environment variable instead.

CHORE: Refactor GitHub Workflow to Use Environment Variable for GCP Region

---

src/index.ts
tsconfig.json

The existing errorMiddleware was only capable of handling errors within resolvers. This has been updated to handle other GraphQL errors as well, such as schema validation errors and query syntax errors.
Previously, only GraphQL errors were being handled through errorMiddleware and the above changes. Error handling for the entire Express application has now been added to address non-GraphQL errors.
---
errorMiddlewareは、リゾルバ内のエラーしかハンドリングできていなかったため、その他のGraphQLエラー（スキーマバリデーションエラー、クエリ構文エラー）なども含めて処理できるよう修正した
errorMiddlewareと1の修正だけでは、GraphQLエラーしかハンドリングできていなかったため、Expressアプリ全体のエラー処理を追加した

FEAT: added error handlings (Apollo Server error handling &  Express error handling)

---

src/index.ts

Set the process.env.NODE_ENV variable to improve performance and security in the production environment.
本番環境でのパフォーマンスとセキュリティの向上を狙って、process.env.NODE_ENV変数を設定する。
[Apollo Server
](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages#:~:text=landing%20page.-,Default%20behavior,-If%20you%20don%27t)
For example, when NODE_ENV is set to production, the Playground can be disabled, reducing security risks.
```
If you don't manually install any plugin that implements renderLandingPage, Apollo Server does the following by default:
In non-production environments (NODE_ENV is not production), Apollo Server installs ApolloServerPluginLandingPageLocalDefault.
In production environments (NODE_ENV is production), Apollo Server installs ApolloServerPluginLandingPageProductionDefault. …
```

FEAT: set process.env.NODE_ENV

---

src/app/membership/wallet/service.ts
src/app/opportunity/participation/usecase.ts

`WalletService.findWalletsForGiveReward`内で呼び出している`WalletRepository.checkIfExistingMemberWallet`は、
引数にuserIdを取る必要があるが、
participation.idを渡す実装になっていたため、結果が取得できていなかった。
そのため、userIdを使うよう修正した。

FIX: fix find member wallet for give reward

---

src/application/domain/experience/evaluation/usecase.ts
src/application/domain/reward/ticketIssuer/controller/resolver.ts
src/application/domain/reward/ticketIssuer/data/converter.ts
src/application/domain/reward/ticketIssuer/data/interface.ts
src/application/domain/reward/ticketIssuer/data/repository.ts
src/application/domain/reward/ticketIssuer/presenter.ts
src/application/domain/reward/ticketIssuer/schema/query.graphql
src/application/domain/reward/ticketIssuer/service.ts
src/application/domain/reward/ticketIssuer/usecase.ts
src/application/provider.ts
src/presentation/graphql/resolver.ts
src/types/graphql.ts

This pull request introduces GraphQL queries for `TicketIssuer`, including support for pagination, filtering, and sorting. Key changes include:
- Added query resolvers for `ticketIssuers` and `ticketIssuer`.
- Implemented input types `GqlTicketIssuerFilterInput` and `GqlTicketIssuerSortInput`.
- Created connections and edges for `TicketIssuer` in the GraphQL schema.
- Updated service and use case layers for the new query functionality.
- Integrated the updates into the GraphQL resolver registry.

Add GraphQL queries for TicketIssuer with pagination

---

docs/ERD.md
docs/schema.dbml
src/application/domain/experience/evaluation/controller/resolver.ts
src/application/domain/experience/evaluation/data/interface.ts
src/application/domain/experience/evaluation/data/repository.ts
src/application/domain/experience/evaluation/data/type.ts
src/application/domain/experience/evaluation/service.ts
src/application/domain/experience/evaluation/usecase.ts
src/application/domain/experience/opportunitySlot/controller/dataloader.ts
src/application/domain/experience/opportunitySlot/controller/resolver.ts
src/application/domain/experience/opportunitySlot/data/type.ts
src/application/domain/experience/opportunitySlot/presenter.ts
src/application/domain/experience/opportunitySlot/schema/type.graphql
src/application/domain/experience/opportunitySlot/service.ts
src/application/domain/experience/opportunitySlot/usecase.ts
src/application/domain/experience/participation/data/repository.ts
src/application/domain/notification/presenter/richmenu/admin/admin_menu.json
src/application/domain/notification/presenter/richmenu/admin/user_menu.json
src/application/domain/notification/presenter/richmenu/const.ts
src/application/domain/notification/presenter/richmenu/user/public_menu.json
src/errors/graphql.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250518145138_create_slot_evaluation_progress_view/migration.sql
src/infrastructure/prisma/migrations/20250518152954_nullable_foreign_user_keys/migration.sql
src/infrastructure/prisma/schema.prisma
src/types/graphql.ts

---
- Updated foreign key constraints (`createdByUser`, `evaluator`) to allow nulls in schema, migrations, and factories.
- Improved evaluation eligibility checks with the `validateEvaluatable` method and new error handling (`AlreadyEvaluatedError`, `CannotEvaluateBeforeOpportunityStartError`).
- Enhanced opportunity slot visitor view by implementing dedicated fetching logic via `visitorViewOpportunitySlot` and including `slotEvaluationProgress`.
- Added `SlotEvaluationProgress` schema integration, including the `v_slot_evaluation_progress` database view and updates to types and domain models.
- Improved error feedback by replacing `InvalidEvaluationStatusError` with a more descriptive `ValidationError`. 
---

Make foreign keys nullable and enhance evaluation logic

---

docs/ERD.md
docs/schema.dbml
package.json
src/application/domain/account/membership/presenter.ts
src/application/domain/account/membership/schema/type.graphql
src/application/domain/account/membership/usecase.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250519132455_nullable_place_name_and_image_in_view/migration.sql
src/infrastructure/prisma/schema.prisma
src/types/graphql.ts

---
- Removed debug `console.log` statements from the membership presenter and use case for cleaner production-level code.
- Simplified optional `address` field handling by removing redundant null-coalescing.
- Updated `MembershipParticipationGeoView` model and schema to set `placeName` and `placeImage` fields as nullable.
- Adjusted associated factory, DBML definitions, and added a placeholder migration to align with the updated schema.
No additional notes.

Remove debug logs and update nullable fields

---

src/application/domain/experience/opportunity/controller/resolver.ts
src/application/domain/experience/opportunitySlot/controller/dataloader.ts

Enhanced the `slots` resolver by introducing support for `filter` and `sort` arguments. Refactored the `createSlotsByOpportunityLoader` function to leverage `createFilterSortAwareHasManyLoaderByKey`, providing more advanced filtering and sorting capabilities for opportunity slot queries.

Add filtering and sorting to opportunity slots resolver

---

src/application/domain/experience/opportunitySlot/data/converter.ts
src/application/domain/experience/opportunitySlot/schema/query.graphql
src/types/graphql.ts

```markdown
This pull request introduces an `ownerId` filter to the `OpportunitySlot` queries. The following changes have been made:
- Added `ownerId` to the `OpportunitySlotFilterInput` field in the GraphQL schema.
- Updated TypeScript definitions to reflect this new filter.
- Modified the query converter to enable filtering by the `ownerId` field.
_No issues linked to this pull request._
```

Add ownerId filter to OpportunitySlot queries

---

src/application/domain/experience/opportunity/data/converter.ts

Opportunity 検索時の State コードによるフィルタリング機能に不具合があったため修正
- OpportunityConverter クラスの opportunityFilter メソッドにおいて、stateCodes フィルタリング条件が誤って filter.cityCodes を使用していたため、正しく filter.stateCodes を使用するように修正しました
- 関連するコードのインデントも整理しました
StateCodes による機会検索が正しく機能するようになります

Fix stateCodes filtering in opportunity search

---

docs/ERD.md
docs/schema.dbml
src/application/domain/experience/reservation/data/converter.ts
src/application/domain/experience/reservation/data/interface.ts
src/application/domain/experience/reservation/schema/mutation.graphql
src/application/domain/experience/reservation/schema/type.graphql
src/application/domain/experience/reservation/service.ts
src/application/domain/experience/reservation/usecase.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250522142751_add_comment_to_reservation/migration.sql
src/infrastructure/prisma/schema.prisma
src/infrastructure/prisma/seeds/domains.ts
src/types/graphql.ts

**Summary of Changes:**
- Added support for an optional `comment` field in reservation creation, propagating it through the service, use case, and database layers.
- Updated Reservation GraphQL schema to include the `comment` field in both mutation and type definitions.
- Added the `comment` column to the Prisma schema with generated migrations and updated database documentation to reflect this change.

Add support for optional comment in reservations

---

src/application/domain/experience/opportunitySlot/schema/type.graphql
src/types/graphql.ts

This pull request modifies the `opportunitySlot` fields in the GraphQL schema to allow null values. Key changes include:
- Updated `isFullyEvaluated`, `numParticipants`, and `numEvaluated` to be nullable.
- Adjusted TypeScript GraphQL types with `Maybe<>` to reflect new nullable status.
- Updated GraphQL resolvers to handle potential `null` values more effectively.
These changes aim to better align the schema with data scenarios where corresponding values might not be available.

Make opportunitySlot fields nullable in GraphQL schema

---

src/application/domain/account/membership/schema/mutation.graphql
src/application/domain/account/membership/service.ts
src/application/domain/experience/opportunitySlot/schema/type.graphql
src/types/graphql.ts

1. **Enhancement of Membership Authorization and Role Assignment**:
- Updated authorization rules in GraphQL schema from `IsCommunityManager` to `IsCommunityOwner`.
- Improved handling of membership status using `GqlMembershipStatus.Joined`.
- Streamlined role assignment logic by commenting out unnecessary membership lookup.
2. **Refactoring Opportunity Slot Fields**:
- Made `isFullyEvaluated`, `numParticipants`, and `numEvaluated` fields nullable in the GraphQL schema.
- Reflected the change in TypeScript GraphQL types by using `Maybe<>`.
- Updated GraphQL resolvers to properly handle nullable values.
- Improved flexibility for data scenarios where the fields might be unavailable.
---

Update membership rules and make opportunity slot fields nullable

---

src/application/domain/notification/line.ts
src/application/domain/notification/presenter/message/switchRoleMessage.ts
src/application/domain/notification/service.ts

This pull request introduces a feature that notifies users when they are granted admin privileges. Key changes include:
- Implementation of a `buildAdminGrantedMessage` function to craft notification messages for new admins.
- Improvement of `safeLinkRichMenuIdToUser` to return a success status, aiding in smoother handling of link operations.
- Enhanced role change logic to automatically send notifications upon admin privilege assignment.

Notify users when granted admin privileges

---

src/application/domain/experience/opportunity/controller/dataloader.ts
src/application/domain/experience/opportunity/controller/resolver.ts
src/presentation/graphql/dataloader/domain/experience.ts

This pull request introduces the following changes:
- Implements a new Dataloader `createIsReservableWithTicketLoader` to streamline opportunity reservation checks.
- Replaces existing resolver logic with the loader for improved performance and readability.
- Updates dataloader utilities to handle composite keys more effectively.

Add `isReservableWithTicket` loader for reservation checks

---

src/application/domain/notification/presenter/message/rejectReservationMessage.ts

This pull request addresses issues related to invalid or empty comments by introducing the following changes:
- Sanitizes and trims input comments using `safeComment`.
- Defaults the text to `fallbackMessage` when `safeComment` is empty.
- Prevents issues caused by non-string or nullish comments.
- Implements the nullish coalescing operator (`??`) to handle nullish values more effectively in the `rejectReservationMessage`.
These updates aim to improve error-handling and ensure consistent fallback behavior.

Ensure fallback message is used for empty or invalid comments

---

src/application/domain/experience/opportunitySlot/schema/mutation.graphql
src/application/domain/experience/opportunitySlot/usecase.ts
src/application/domain/notification/presenter/message/cancelOpportunitySlotMessage.ts
src/application/domain/notification/presenter/message/rejectReservationMessage.ts
src/application/domain/notification/service.ts
src/types/graphql.ts

- Extended `pushCancelOpportunitySlotMessage` to handle an optional comment parameter.
- Updated the GraphQL schema to include `comment` in `OpportunitySlotSetHostingStatusInput`.
- Modified message builders to use custom comments or fallback messages.
- Improved apology messages with dynamic text based on provided comments.

Add comment support for cancel opportunity slot notifications

---

src/application/domain/account/user/controller/resolver.ts
src/application/domain/account/user/usecase.ts
src/infrastructure/prisma/seeds/domains.ts

- Implemented `canCurrentUserViewPhoneNumber` to determine if a user can view another user's phone number based on relationships like reservations or participant links.
- Integrated the new permission logic into the `phoneNumber` field resolver within the system.
- Refactored domain seeding to correct reservation and participation status logic, ensuring accurate and randomized status assignment

Add permission logic for viewing user phone numbers

---

src/application/domain/experience/reservation/usecase.ts

- Added logic to bypass `validateReservable` validation for opportunity ID `cmc07866s0002s60nuuk8jakk`.
- Special case handling ensures that standard validation checks are not unnecessarily triggered.

Skip reservation validation for specific opportunity ID

---

docs/ERD.md
docs/schema.dbml
src/application/domain/account/identity/didIssuanceRequest/controller/dataloader.ts
src/application/domain/account/identity/didIssuanceRequest/schema/type.graphql
src/application/domain/account/identity/didIssuanceRequest/service.ts
src/application/domain/account/user/controller/resolver.ts
src/application/domain/account/user/data/type.ts
src/application/domain/account/user/presenter.ts
src/application/domain/account/user/schema/type.graphql
src/application/domain/experience/evaluation/usecase.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/controller/resolver.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/data/converter.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/data/interface.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/data/repository.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/data/type.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/presenter.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/schema/query.graphql
src/application/domain/experience/evaluation/vcIssuanceRequest/schema/type.graphql
src/application/domain/experience/evaluation/vcIssuanceRequest/service.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/usecase.ts
src/application/provider.ts
src/application/view/presenter.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250624084353_link_evaluation_to_vc/migration.sql
src/infrastructure/prisma/schema.prisma
src/presentation/graphql/dataloader/domain/account.ts
src/presentation/graphql/resolver.ts
src/types/graphql.ts

This pull request introduces complete support for VC Issuance Request handling in the GraphQL layer, including schema, resolvers, and related services. Key features and updates include:
- **GraphQL Enhancements**:
- Added `VCIssuanceRequest`, `DidIssuanceRequest`, and associated types to the GraphQL schema.
- Defined queries for fetching VC and DID issuance requests with filtering, pagination, and sorting options.
- Integrated `VCIssuanceRequestResolver` and `DidIssuanceRequestResolver` into the GraphQL implementation.
- **Service Enhancements**:
- Introduced dedicated services (`VCIssuanceRequestService`) and loaders for fetching, transforming, and processing data related to issuance requests.
- Implemented methods to handle filtering, sorting, and querying issuance requests efficiently …

Add support for VC Issuance Request handling in GraphQL

---

src/application/domain/experience/reservation/validator.ts
src/errors/graphql.ts

開催日時の1週間前をきったら、予約できない制限を前日（24時間前）まで予約できるようにした
client: https://github.com/Hopin-inc/civicship-portal/pull/371

fix: reservation limit 7days ago -> 1days ago

---

src/application/domain/experience/opportunity/data/converter.ts
src/application/domain/experience/opportunity/schema/mutation.graphql
src/application/domain/experience/opportunity/service.ts
src/application/domain/experience/opportunity/usecase.ts
src/application/domain/experience/opportunitySlot/schema/mutation.graphql
src/application/domain/utils.ts
src/infrastructure/prisma/client.ts
src/presentation/graphql/rule.ts
src/presentation/middleware/auth.ts
src/types/graphql.ts
src/types/server.ts

---
This pull request introduces several improvements and features aimed at granting administrative users enhanced access controls and operational flexibility. Key updates include:
- **Access Control Enhancements**: 
- Admin users can bypass opportunity ownership, community restrictions, and role-based access checks across GraphQL rules, improving administrative workflows.
- Introduced admin API key authentication bypass for streamlined admin actions.
- **Schema and Data Handling Updates**:
- Updated the `OpportunityCreateInput` schema to support `slots` and `relatedArticleIds`, and removed outdated fields.
- Incorporated optional `inputUserId` parameter for admins to retrieve user-specific data with `getCurrentUserId`.
- Added `isAdmin` field to `LoggedInUserInfo` type for enhanced role …

Allow admins enhanced access control and functionality

---

src/application/domain/notification/service.ts

- Added validation to ensure `identity.communityId` matches `ctx.communityId`.  
- Prevents incorrect LINE identity assignment in scenarios with multiple communities.

Fix LINE identity check in switchRichMenuByRole

---

src/application/domain/experience/opportunitySlot/schema/mutation.graphql
src/application/domain/experience/opportunitySlot/usecase.ts
src/application/domain/experience/participation/statusHistory/service.ts
src/types/graphql.ts

This pull request implements the following changes:
1. **Refactor:**
- Pass `currentUserId` explicitly as a parameter in `bulkCreateStatusHistoriesForCancelledOpportunitySlot`.
- Removed dependency on the `getCurrentUserId` function, simplifying the code and enhancing testability.
2. **Feature:**
- Add a `createdBy` field to the `OpportunitySlotSetHostingStatusInput` in the GraphQL schema.
- Update the related TypeScript type, `GqlOpportunitySlotSetHostingStatusInput`, to include the `createdBy` field.
- Facilitates tracking the admin responsible for setting hosting statuses.

Refactor and enhance hosting status management

---

src/application/domain/content/article/data/converter.ts

- **Summary of Changes:**  
Fixed an issue where `publishedAt` was not being consistently set during article updates. This change introduces logic to assign the current date to the `publishedAt` field within the `update` method. Additionally, TODO comments have been added to outline necessary future database changes to enforce this behavior programmatically.
- **Impacted Areas in the Application:**  
- Article updates logic
- **Testing Steps:**  
1. Update an article and verify that the `publishedAt` field is correctly set to the current date if not already defined.
2. Examine logs for any unexpected errors or issues.
- **Notes for Reviewers:**  
- Check the `update` method implementation for accuracy and edge-case handling.
- Review the added TODO comments for clarity on upcoming …

Ensure `publishedAt` is always set when updating articles

---

src/application/domain/account/nft-wallet/controller/dataloader.ts
src/application/domain/account/nft-wallet/data/type.ts
src/application/domain/account/nft-wallet/presenter.ts
src/application/domain/account/nft-wallet/schema/type.graphql
src/application/domain/account/user/controller/resolver.ts
src/application/domain/account/user/schema/type.graphql
src/presentation/graphql/dataloader/domain/account.ts
src/types/graphql.ts

- NftWalletPresenterを作成し、NftWalletの詳細を取得するメソッドを実装
- NftWallet用のDataLoaderを作成し、ユーザーIDに基づいてNftWalletを取得
- NftWalletのGraphQL型定義を追加し、User型にnftWalletフィールドを追加
- アカウントドメインのDataLoaderを更新し、nftWalletを含めるように変更
- GqlNftWallet型をGraphQLの型定義に追加
これにより、ユーザーのNftWallet情報が取得可能になりました。

NftWallet関連の機能を追加

---

src/application/domain/experience/participation/data/converter.ts
src/application/domain/experience/participation/service.ts

Ensures that participations are linked to the appropriate community by including `communityId` in the creation inputs. Updated converter and service logic to facilitate this improvement.

Add community association to participation creation

---

src/application/domain/account/membership/data/type.ts

- PrismaのmembershipSelectDetailにuserとcommunityの選択フィールドを追加
- ユーザーとコミュニティに関連するデータの取得を強化

membershipSelectDetailにuserとcommunityフィールドを追加

---

codegen.yaml
src/application/domain/account/wallet/schema/type.graphql
src/infrastructure/prisma/schema.prisma
src/presentation/graphql/schema/utils.graphql
src/types/graphql.ts

This pull request updates the GraphQL schema to utilize `BigInt` for the `currentPoint` and `accumulatedPoint` fields. It includes the following changes:
- Modified `currentPoint` and `accumulatedPoint` fields from `Int` to `BigInt`.
- Added support for the `BigInt` scalar type in the GraphQL configuration and codegen.
- Adjusted the resolver and type definitions to ensure compatibility with `BigInt`.

Update GraphQL schema to use BigInt for point fields

---

src/application/domain/account/wallet/service.ts
src/application/domain/transaction/data/interface.ts
src/application/domain/transaction/data/repository.ts
src/application/domain/transaction/service.ts

```
{
"insertId": "........G_wgI0pG_ipC6fGcA4V6eY71",
"jsonPayload": {
"message": "Invalid prisma.$queryRawTyped() invocation:\n\nTransaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5236 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.",
"metadata": {
"severity": "ERROR",
"target": "$queryRawTyped"
}
},
"logName": "projects/co-creation-dao-prod/logs/winston_log",
"payload": "jsonPayload",
"receiveLocation": "us-central1",
"receiveTimestamp": "2025-07-08T15:43:25.787231285Z",
"resource": {
"type": "cloud_run_revision",
"labels": {
"configuration_name": "prod-civicship-api",
"location": …
```

Refactor wallet service and simplify points-related API

---

src/infrastructure/prisma/client.ts

This pull request introduces logging for transaction duration and slow Prisma queries, along with a new timeout configuration for certain database operations.
- **Transaction Duration Logs**: Logs are added to monitor execution time in `onlyBelongingCommunity` and `bypassRls` methods, with warnings for durations exceeding 3000ms.
- **Slow Query Logs**: Added logs to detect and warn about Prisma queries taking longer than 1 second.
- **Timeout Configuration**: Implemented a 10-second transaction timeout in `setRls` and `bypassRls` methods to prevent indefinite execution. 
These changes improve performance monitoring and ensure better transaction handling.

Add logging and timeout mechanism for transactions

---

src/infrastructure/prisma/client.ts

###Error
```
{
"insertId": "........G_wgI0pG_ipC6fGcA4V6eY71",
"jsonPayload": {
"message": "Invalid prisma.$queryRawTyped() invocation:\n\nTransaction API error: Transaction already closed: A query cannot be executed on an expired transaction. The timeout for this transaction was 5000 ms, however 5236 ms passed since the start of the transaction. Consider increasing the interactive transaction timeout or doing less work in the transaction.",
"metadata": {
"severity": "ERROR",
"target": "$queryRawTyped"
}
},
"logName": "projects/co-creation-dao-prod/logs/winston_log",
"payload": "jsonPayload",
"receiveLocation": "us-central1",
"receiveTimestamp": "2025-07-08T15:43:25.787231285Z",
"resource": {
"type": "cloud_run_revision",
"labels": {
"configuration_name": "prod-civicship-api",
"location": …
```

Add transaction timeout configuration in Prisma client methods

---

src/application/domain/experience/opportunity/data/converter.ts

This pull request refactors the `create` method in the opportunity data converter for improved clarity and consistency. Key changes include:
- Conversion of the `create` method to an arrow function.
- Renaming variables for better readability (`prop` to `rest`, `currentUserId` to `userId`).
- Simplification of conditional logic using optional chaining and `.filter(Boolean)`.
- Streamlining of `slots`, `requiredUtilityIds`, and `relatedArticleIds` handling to enhance readability. 
These adjustments aim to maintain the functionality while making the code more maintainable and easier to understand.
---

Refactor `create` method in opportunity data converter

---

src/application/domain/experience/opportunity/data/converter.ts
src/application/domain/experience/opportunity/schema/mutation.graphql
src/application/domain/experience/opportunity/service.ts
src/types/graphql.ts

This pull request refactors the opportunity input logic and schema to improve clarity and reduce redundancy:
- Simplified input data conversion logic by directly connecting `placeId` and adding support for `requiredUtilityIds` and `relatedArticleIds`.
- Removed the unused `validatePlaceInput` function along with related imports and redundant validation logic.
- Updated the Opportunity schema by:
- Replacing the `place` field with `placeId`.
- Adding the `relatedArticleIds` field for linking articles.
- Removing `capacity`, `startsAt`, and `endsAt` fields for streamlined structure.
- Applied changes consistently in the GraphQL schema and TypeScript types.

Refactor opportunity input logic and schema for clarity

---

src/application/domain/experience/evaluation/data/converter.ts
src/application/domain/experience/evaluation/schema/query.graphql
src/types/graphql.ts

This pull request adds support for filtering evaluations by `communityId`.
- Introduced a `communityId` filter in the evaluation data converter.
- Extended the GraphQL schema by adding the `communityId` field to `EvaluationFilterInput`.
- Updated TypeScript types to reflect schema changes.
These changes enhance the flexibility and precision of evaluation data queries by allowing filtering based on community ID.  
N/A  
N/A

Add communityId filtering to evaluations

---

src/__tests__/unit/experience/opportunitySlot.service.test.ts
src/application/domain/experience/opportunitySlot/controller/resolver.ts
src/application/domain/experience/opportunitySlot/data/converter.ts
src/application/domain/experience/opportunitySlot/data/interface.ts
src/application/domain/experience/opportunitySlot/data/repository.ts
src/application/domain/experience/opportunitySlot/presenter.ts
src/application/domain/experience/opportunitySlot/schema/mutation.graphql
src/application/domain/experience/opportunitySlot/service.ts
src/application/domain/experience/opportunitySlot/usecase.ts
src/types/graphql.ts

This pull request introduces the functionality for creating opportunity slots and updating their hosting status with capacity parameters. Additionally, a GraphQL mutation has been added to facilitate the creation of opportunity slots.
- Added the ability to create opportunity slots.
- Introduced a capacity parameter for updating hosting status in `OpportunitySlot`.
- Implemented a GraphQL mutation for creating opportunity slots.

Add opportunity slot creation and capacity update features

---

docs/ERD.md
docs/schema.dbml
src/application/domain/account/wallet/validator.ts
src/application/domain/experience/reservation/data/converter.ts
src/application/domain/experience/reservation/data/interface.ts
src/application/domain/experience/reservation/schema/mutation.graphql
src/application/domain/experience/reservation/schema/type.graphql
src/application/domain/experience/reservation/service.ts
src/application/domain/experience/reservation/usecase.ts
src/application/domain/transaction/data/converter.ts
src/application/domain/transaction/data/interface.ts
src/application/domain/transaction/schema/type.graphql
src/application/domain/transaction/service.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250723110115__add_participant_count_with_point_to_reservations/migration.sql
src/infrastructure/prisma/migrations/20250723120853_add_opportunity_reservation_reasons_to_transaction_reason/migration.sql
src/infrastructure/prisma/migrations/20250723132558_connect_transactions_to_reservations/migration.sql
src/infrastructure/prisma/migrations/20250723153713_add_participant_count_with_point_to_reservations/migration.sql
src/infrastructure/prisma/schema.prisma
src/infrastructure/prisma/seeds/index.ts
src/types/graphql.ts

- `t_reservations`テーブルに`participant_count_with_point`カラムを追加し、参加者数に基づくポイントの管理を実装。
- トランザクション理由に`OPPORTUNITY_RESERVATION_CREATED`などの新しい理由を追加。
- 予約作成時にポイントを転送するロジックを追加し、関連するGraphQLスキーマとTypeScript型定義を更新。

Mutation reservationCreate で、ポイントを使って予約できるようにする

---

src/application/domain/account/membership/data/type.ts
src/application/domain/account/membership/presenter.ts
src/application/domain/account/membership/schema/type.graphql
src/types/graphql.ts

neo88のportalからplacesのフィーチャフラグをoffにする
This pull request removes redundant and unused code for membership participation and hosting:
- Eliminates unnecessary logic in `MembershipPresenter`.
- Removes unused fields from type definitions.
- Deletes unused GraphQL types and fields associated with membership participation and hosting.
N/A

Remove redundant membership-related logic and unused fields

---

src/application/domain/location/master/controller/resolver.ts
src/application/domain/location/master/data/converter.ts
src/application/domain/location/master/schema/query.graphql
src/application/domain/location/master/service.ts
src/application/domain/location/master/usecase.ts
src/types/graphql.ts

This pull request introduces sorting capability for the cities list in the Master module and the corresponding GraphQL schema. This enhancement allows users to fetch sorted lists of cities based on specific criteria, thereby improving the functionality and user experience.

Add sorting functionality to cities list

---

src/application/domain/experience/opportunity/usecase.ts
src/application/domain/location/place/data/converter.ts
src/application/domain/location/place/schema/query.graphql
src/types/graphql.ts

- Added validation for admin permissions in opportunity filter logic.
- Added support for `communityId` as a filter in Place queries.

Add admin validation and community filter support
