Hopin-inc/civicship-api

.github/workflows/deploy-to-cloud-run-prd.yml

Added a new GitHub workflow for deploying to the prd CloudRun environment.
To allow for separate configurations between the prd and dev envs, the workflow was created as a separate file.

CHORE: GitHub Workflow to deploy to prd CloudRun

---

.github/workflows/deploy-to-cloud-run-dev.yml
.github/workflows/deploy-to-cloud-run-prd.yml

combine GCP credentials into a single variable.

REFACTOR: combine GCP credentials into a single variable

---

.github/workflows/deploy-to-cloud-run-dev.yml
.github/workflows/deploy-to-cloud-run-prd.yml
Dockerfile.batch

Added github workflow to deploy batch

chore: deploy batch

---

src/application/domain/account/community/presenter.ts
src/application/domain/account/identity/presenter.ts
src/application/domain/account/membership/presenter.ts
src/application/domain/account/user/presenter.ts
src/application/domain/account/wallet/presenter.ts
src/application/domain/content/article/presenter.ts
src/application/domain/experience/evaluation/presenter.ts
src/application/domain/experience/opportunity/data/converter.ts
src/application/domain/experience/opportunity/presenter.ts
src/application/domain/experience/opportunity/schema/query.graphql
src/application/domain/experience/opportunity/service.ts
src/application/domain/experience/opportunity/usecase.ts
src/application/domain/experience/opportunitySlot/presenter.ts
src/application/domain/experience/participation/presenter.ts
src/application/domain/experience/participation/statusHistory/service.ts
src/application/domain/experience/reservation/data/converter.ts
src/application/domain/experience/reservation/presenter.ts
src/application/domain/experience/reservation/validator.ts
src/application/domain/location/master/presenter.ts
src/application/domain/location/place/presenter.ts
src/application/domain/reward/ticket/presenter.ts
src/application/domain/reward/ticketClaimLink/presenter.ts
src/application/domain/reward/ticketIssuer/presenter.ts
src/application/domain/reward/utility/presenter.ts
src/index.ts
src/presentation/graphql/schema/utils.graphql
src/presentation/graphql/server.ts
src/types/graphql.ts

This pull request includes several enhancements and refinements across the codebase:
- **Refactor:** Simplified CORS header handling by removing redundant logic in GraphQL `formatError` and Express middleware, enhancing code maintainability.
- **Feature:** Added `DateTimeRangeFilter` input type to the GraphQL schema for improved range-based filtering, replacing individual date fields with `slotDateRange`.
- **Feature:** Included `__typename` field in GraphQL responses to ensure consistent payload structure and improved typing.
- **Feature:** Validated slot creation to require at least 7 days' notice.
- **Refactor:** Renamed `opportunitySlot.id` to `opportunitySlotId` for naming consistency.

Refactor and improve GraphQL schema and error handling

---

src/__tests__/integration/pointTransfer/ticketClaim.test.ts
src/__tests__/unit/experience/evaluation.service.test.ts
src/__tests__/unit/experience/reservation.validator.test.ts
src/application/domain/content/article/service.ts
src/application/domain/experience/evaluation/service.ts
src/application/domain/experience/opportunity/service.ts
src/application/domain/experience/opportunitySlot/data/converter.ts
src/application/domain/experience/opportunitySlot/schema/query.graphql
src/application/domain/experience/participation/service.ts
src/application/domain/experience/reservation/schema/mutation.graphql
src/application/domain/experience/reservation/usecase.ts
src/application/domain/experience/reservation/validator.ts
src/application/domain/reward/ticket/schema/mutation.graphql
src/application/domain/reward/ticket/service.ts
src/application/domain/reward/utility/service.ts
src/errors/graphql.ts
src/presentation/graphql/schema/error.graphql
src/types/graphql.ts

---
This pull request introduces comprehensive changes to improve error handling and code maintainability across the codebase, along with some new features:
- **Error Handling Enhancements:**
- Added new GraphQL error types for clearer and more specific error responses (`AuthenticationError`, `ReservationConflictError`, etc.).
- Introduced and standardized `GqlErrorCode` enums.
- Consolidated error classes (e.g., replaced custom error classes with reusable ones like `ValidationError` and `NotFoundError`).
- **Schema and Payload Updates:**
- Expanded payloads for reservation mutations to include additional error types.
- Simplified GraphQL schema definitions by removing unused or redundant entries.
- **Test Improvements:**
- Improved test robustness by updating test logic with mock …

Refactor and enhance error handling in GraphQL and services

---

docs/ERD.md
docs/schema.dbml
src/application/domain/experience/evaluation/controller/resolver.ts
src/application/domain/experience/evaluation/data/interface.ts
src/application/domain/experience/evaluation/data/repository.ts
src/application/domain/experience/evaluation/data/type.ts
src/application/domain/experience/evaluation/service.ts
src/application/domain/experience/evaluation/usecase.ts
src/application/domain/experience/opportunitySlot/controller/dataloader.ts
src/application/domain/experience/opportunitySlot/controller/resolver.ts
src/application/domain/experience/opportunitySlot/data/type.ts
src/application/domain/experience/opportunitySlot/presenter.ts
src/application/domain/experience/opportunitySlot/schema/type.graphql
src/application/domain/experience/opportunitySlot/service.ts
src/application/domain/experience/opportunitySlot/usecase.ts
src/application/domain/experience/participation/data/repository.ts
src/application/domain/notification/presenter/richmenu/admin/admin_menu.json
src/application/domain/notification/presenter/richmenu/admin/user_menu.json
src/application/domain/notification/presenter/richmenu/const.ts
src/application/domain/notification/presenter/richmenu/user/public_menu.json
src/errors/graphql.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250518145138_create_slot_evaluation_progress_view/migration.sql
src/infrastructure/prisma/migrations/20250518152954_nullable_foreign_user_keys/migration.sql
src/infrastructure/prisma/schema.prisma
src/types/graphql.ts

1. **Feature:**  
- Added validation for `participation` existence and evaluatability in the `createEvaluation` use case.
- Implemented validation using `participationService` and `evaluationService` with `Promise.all` for efficient checks.
- Ensures proper error handling and data integrity before creating evaluations.
2. **Bug Fix:**  
- Updated LIFF URLs in user, admin, and public menu configurations (`menu JSON files`).
- Replaced outdated rich menu IDs in `const.ts` with updated IDs.
- Ensures the system remains consistent with the current LIFF application structure.
Please review the updated changes, particularly the integration and checks in validation logic and menu configuration updates.

Update evaluation validation and LIFF configurations

---

src/application/domain/experience/evaluation/data/interface.ts
src/application/domain/experience/evaluation/presenter.ts
src/application/domain/experience/evaluation/service.ts
src/application/domain/experience/evaluation/usecase.ts
src/application/domain/experience/participation/data/interface.ts
src/application/domain/experience/participation/data/repository.ts
src/application/domain/experience/participation/data/type.ts
src/application/domain/experience/participation/service.ts

---
This pull request contains several updates focusing on the handling of evaluations, opportunity slots, and participation validation. Below are the highlights:
- **Code Refactoring**
- Simplified evaluation validation by moving logic to a dedicated `validateEvaluatable` method.
- Updated repository and service layers for better modularity and error handling.
- Removed redundant code and improved timezone-specific validation checks.
- **Enhancements**
- Introduced `findParticipationWithSlotOrThrow` to include slot details in participations.
- Added validations to ensure evaluation eligibility and participation existence before creating evaluations.
- Implemented `visitorViewOpportunitySlot` use case for querying opportunity slots directly.
- **Bug Fixes**
- Updated LIFF URLs and menu …

Refactor and improve evaluation and slot management features

---

debugScripts/pushTestMessage.ts
src/application/domain/experience/opportunitySlot/data/converter.ts
src/application/domain/experience/opportunitySlot/schema/query.graphql
src/application/domain/notification/service.ts
src/types/graphql.ts

1. **Centralized LINE UID Resolution:**
- Introduced the `resolveLineUid` method in the notification service to centralize and simplify UID resolution logic.
- Removed repetitive UID resolution code across various methods.
- Deprecated the unused `LOCAL_UID` export from the service, now redefined within debug scripts.
2. **Updated URLs for Assets and Navigation Links:**
- Replaced outdated storage URLs with updated Google Cloud Storage links for images and thumbnails used in the application.
- Updated LIFF app IDs and changed redirect URLs (e.g., reservation pages, participation flows, and admin pages) to align with the new framework and resources.
These changes aim to improve code maintainability and ensure all assets and redirects point …

Refactor notification service and update URLs

---

src/application/domain/account/membership/schema/mutation.graphql
src/application/domain/account/membership/service.ts
src/application/domain/experience/opportunitySlot/schema/type.graphql
src/application/domain/transaction/controller/resolver.ts
src/application/domain/transaction/data/converter.ts
src/application/domain/transaction/data/interface.ts
src/application/domain/transaction/presenter.ts
src/application/domain/transaction/schema/mutation.graphql
src/application/domain/transaction/schema/query.graphql
src/application/domain/transaction/service.ts
src/application/domain/transaction/usecase.ts
src/types/graphql.ts

This pull request refactors and enhances several aspects of the existing codebase to improve functionality, readability, and alignments with data requirements.
1. **Transaction Input Handling**
- Simplified grant/issue transaction input by removing redundant fields like `fromWalletId` and `communityId`.
- Updated method signatures to accept deconstructed arguments.
- Introduced `buildTransactionWhereInput` to support complex, recursive query filters.
- Added wallet type filters and logical operators (`and`, `or`, `not`) to query inputs.
- Adjusted related layers and removed unused console logs for consistency.
2. **Membership Authorization and Role Assignments**
- Updated GraphQL schema using `IsCommunityOwner` for authorization rules instead of `IsCommunityManager`.
- Streamlined role …

Refactor and enhance transaction handling, roles, and schema

---

src/application/domain/notification/presenter/richmenu/const.ts

Assign the proper rich menu for the production environment. Adjustments are made to ensure that the configuration aligns with the production standards. No breaking changes introduced.

Assign production rich menu

---

src/application/domain/notification/service.ts

```
This pull request fixes an issue with reservation notification redirect URLs by appending `?mode=approval` to ensure consistent handling of approval flows.
- Updated the `redirectUrl` in reservation notifications to include the `?mode=approval` query parameter for seamless approval flow handling.
```

Fix approval mode in reservation notification redirect URL

---

docs/ERD.md
docs/schema.dbml
src/__tests__/unit/account/identity.service.test.ts
src/application/domain/account/identity/service.ts
src/application/domain/account/identity/usecase.ts
src/application/domain/account/membership/data/type.ts
src/application/domain/experience/opportunitySlot/data/type.ts
src/application/domain/experience/reservation/data/type.ts
src/application/domain/notification/line.ts
src/application/domain/notification/service.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250701014727_link_identity_to_community/migration.sql
src/infrastructure/prisma/schema.prisma

- **Updates to LINE UID Extraction**:  
Introduced `communityId` validation when extracting LINE UIDs to prevent mismatches across shared user identities in multiple communities. Adjusted relevant methods and added logging for missing cases.
- **Enhancements in Data Fetching**:  
Extended nested includes in user-related queries to fetch community data alongside identities for improved data richness, applied across reservation, opportunitySlot, and membership data types.
- **Database Schema Updates**:  
Added `community_id` relation to the identity model, updated migration files, Prisma schema, and documentation (DBML, ERD). Ensured proper cascading and nullable rules in the database schema.
- **User Profile Validation for LINE API**:  
Implemented `safeGetUserProfile` to validate user …

Add community-specific validations and enhancements

---

codegen.yaml
src/application/domain/account/wallet/schema/type.graphql
src/infrastructure/prisma/schema.prisma
src/presentation/graphql/schema/utils.graphql
src/types/graphql.ts

Reverts Hopin-inc/civicship-api#332

Revert "Update GraphQL schema to use BigInt for point fields"

---

src/application/domain/experience/evaluation/data/type.ts
src/application/domain/experience/evaluation/vcIssuanceRequest/service.ts
src/presentation/batch/requestDIDVC/requestVC.ts
src/presentation/batch/syncDIDVC/syncVC.ts

---
This pull request addresses an issue related to VC issuance when the User DID is missing. 
- Introduced a `markIssuanceStatus` method to allow flexible updates for issuance states.
- Updated the process to mark issuance as pending instead of failing in cases where the User DID is not found.
- Enhanced overall error handling with better logging and updated status flow.

Handle missing User DID by marking VC issuance as pending

---

codegen.yaml
docs/ERD.md
docs/schema.dbml
src/__tests__/unit/account/wallet.validator.test.ts
src/application/domain/account/wallet/schema/type.graphql
src/application/domain/account/wallet/validator.ts
src/application/domain/content/image/service.ts
src/errors/graphql.ts
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/schema.prisma
src/presentation/graphql/resolver.ts
src/presentation/graphql/scalar/index.ts
src/presentation/graphql/schema/utils.graphql
src/types/graphql.ts

- Improved BigInt typing within GraphQL types and resolvers.
- Fixed handling of BigInt for better compatibility and functionality in GraphQL operations.
- Additional refactoring to enhance code maintainability and clarity.
No breaking changes are introduced.

Refactor and fix BigInt handling in GraphQL

---

src/application/view/data/converter.ts
src/presentation/graphql/scalar/index.ts

- フィルター条件において、`opportunitySlot`と`reservation`の両方を考慮するために、条件をOR条件に変更しました。
- `startsAt`の条件も同様にOR条件に更新しました。

ViewConverterの条件をOR条件に変更

---

src/application/domain/account/identity/didIssuanceRequest/service.ts
src/presentation/batch/requestDIDVC/index.ts
src/presentation/batch/requestDIDVC/requestDID.ts
src/presentation/batch/requestDIDVC/requestVC.ts
src/presentation/batch/syncDIDVC/syncDID.ts
src/presentation/batch/syncDIDVC/syncVC.ts

Reverts Hopin-inc/civicship-api#356

Revert "Refactor and enhance DID and VC issuance processes"

---

src/application/domain/account/identity/didIssuanceRequest/service.ts
src/presentation/batch/requestDIDVC/index.ts
src/presentation/batch/requestDIDVC/requestDID.ts
src/presentation/batch/requestDIDVC/requestVC.ts
src/presentation/batch/syncDIDVC/syncDID.ts
src/presentation/batch/syncDIDVC/syncVC.ts

Reverts Hopin-inc/civicship-api#359

Revert "Revert "Refactor and enhance DID and VC issuance processes""

---

src/presentation/middleware/firebase-phone-auth.ts

- Improved logging for better debugging in Firebase phone authentication middleware.
- Standardized string quotes throughout the middleware for code consistency.
No additional issues were linked to this pull request.

Enhance logging and standardize string quotes in Firebase middleware

---

src/application/domain/experience/reservation/validator.ts
src/errors/graphql.ts

Reverts Hopin-inc/civicship-api#297

Revert "fix: reservation limit 7days ago -> 1days ago"

---

src/application/domain/experience/reservation/validator.ts
src/errors/graphql.ts

Reverts Hopin-inc/civicship-api#383

Revert "Revert "fix: reservation limit 7days ago -> 1days ago""

---

src/application/view/data/converter.ts
src/application/view/usecase.ts

Added a `communityId` filter to both participation and article queries to support filtering data based on community context.

Add communityId filter to queries

---

src/application/view/data/converter.ts

- Enhanced the participation filter to include detailed community-specific constraints.
- Improves accuracy in filtering based on community-defined parameters.
- No breaking changes introduced.

Refine participation filter logic

---

src/application/domain/experience/opportunity/data/converter.ts

This pull request introduces a validation mechanism to filter out empty or invalid IDs in the data conversion logic, ensuring the reliability and correctness of the data processing pipeline.
- Added checks to handle and exclude invalid or empty IDs during data conversion.

Add validation to filter invalid and empty IDs

---

src/application/domain/experience/opportunity/data/converter.ts

```
Refactors the logic in the converter responsible for property validation and mapping to improve code readability and maintainability.
```

Refactor property validation and mapping logic

---

src/application/view/data/converter.ts
src/presentation/batch/checkReservationParticipationConsistency.ts

- Refactored property validation and mapping logic in the opportunity data converter for improved maintainability.
- Introduced validation to filter out empty or invalid IDs, ensuring cleaner data processing.

Refactor validation and mapping in opportunity converter

---

src/application/domain/account/community/config/service.ts
src/application/domain/notification/service.ts

ref: https://github.com/Hopin-inc/civicship-portal/issues/492, https://github.com/Hopin-inc/civicship-portal/issues/574
ログ調べたんですが失敗している跡はなく
https://4hopin.slack.com/archives/C05S019U685/p1755596712944209
https://4hopin.slack.com/archives/C05S019U685/p1755596705956139
- 手前のステップで失敗している
- 何らかの外的要因（LINE ブロックしていたり通信状況だったり）
かなと思われます。ひとまず実装はそのままにログを拡充してみたので、これで静観でいいかなと思いますがレビューもらいたいです！
- **switchRichMenuByRole**: リッチメニューのリンク操作に成功・失敗時の詳細ログを追加
- **switchRichMenuByRole**: LIFF設定取得時のtry-catchエラーハンドリングを追加
- **pushReservationAppliedMessage**: LIFF設定取得とLINEクライアント作成のエラーハンドリング追加
- **ログ情報の充実**: デバッグに必要な情報（communityId、userId、lineUid等）を含めたログ追加
- **コードフォーマット**: インデントの統一とMessagingApiClientのimport追加
- **getLineRichMenuIdByType**: データベースクエリ失敗時のエラーハンドリング追加
- **getLineRichMenuIdByType**: メニューが見つからない場合の適切なログ出力
- …

リッチメニューと通知に関するログ充実とエラーハンドリング

---

docs/ERD.md
docs/schema.dbml
src/infrastructure/prisma/factories/__generated__/index.ts
src/infrastructure/prisma/migrations/20250930002211_add_merkle_proofs_in_transactions/migration.sql
src/infrastructure/prisma/schema.prisma

- feat: Add MerkleProofs and MerkleCommits schema with factories and relationships

Cloud Agent用のテーブル追加

---

README.md
src/application/domain/experience/opportunity/schema/mutation.graphql
src/application/domain/experience/opportunity/service.ts
src/presentation/middleware/logger.ts
src/types/graphql.ts

This pull request improves the logging middleware to handle and log raw `multipart/form-data` requests. It also refactors the image upload logic to ensure old images are deleted before uploading new ones in the opportunity service. Additionally, it introduces a new `pointsRequired` field to the GraphQL types and mutations to enhance data handling.

Enhance logging and refactor image upload logic.

---

src/application/domain/location/place/data/converter.ts
src/application/domain/location/place/schema/query.graphql
src/types/graphql.ts

```
This pull request adds support for filtering Place queries based on a `communityId`. It introduces necessary code updates to handle this feature.
```

Add communityId filter to Place queries.
